---

kind: Service
apiVersion: v1
metadata:
  name: pyecho
  labels:
     app: pyecho
spec:
  selector:
    app: pyecho
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pyecho
  name: pyecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyecho
  template:
    metadata:
      labels:
        app: pyecho
    spec:
      restartPolicy: Always
      containers:
      - name: pyecho
        image: violenti/pyecho:0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 100Mi
            cpu: 0.1
          limits:
            memory: 100Mi
            cpu: 0.1
